security:
  jwt:
    secret: SecretKeyToGenJWTs
    expirationTime: 860000000
    tokenPrefix: "Bearer "
    headerString: "Authorization"

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

  h2:
    console:
      enabled: true

server:
  port: 10020

logging:
  level:
    liquibase: DEBUG