security:
  jwt:
    secret: SecretKeyToGenJWTs
    expirationTime: 860000000
    tokenPrefix: "Bearer "
    headerString: "Authorization"

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hongshu_development?autoReconnect=true&createDatabaseIfNotExist=true
    &characterEncoding=utf8&characterSetResults=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: hongshu
    password: hongshupassword

  h2:
    console:
      enabled: true


logging:
  level:
    liquibase: INFO

server:
  port: 9700
