security:
  jwt:
    secret: SecretKeyToGenJWTs
    expirationTime: 860000000
    tokenPrefix: "Bearer "
    headerString: "Authorization"
  allowedOrigins:
  - http://www.test.packagebutler.com

server:
  port: 10020

packagebutler:
  baseUrl:
    logistics: http://localhost:10000/
    payment: http://localhost:10010/
    member: http://localhost:10030/
    order: http://localhost:10040/
