logging:
  pattern:
    dateformat: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z', UTC"

spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog-master.yaml

hashid:
  salt: e5432ecb4471460e8797758062f7f7a7
  length: 8
  alphabet: ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789
